// <auto-generated />
namespace MyGame.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class fig2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fig2));
        
        string IMigrationMetadata.Id
        {
            get { return "201810152132378_fig2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
