//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyGame.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Login
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Nickname required.")]
        [StringLength(30, MinimumLength = 3, ErrorMessage = "Nickname should be at least 3 symbols and less then 30 symbols length.")]
        [RegularExpression(@"^[a-zA-Z]\w*", ErrorMessage = "Nickname has to begin from a letter.")]
        public string Nickname { get; set; }

        [Required(ErrorMessage = "Password required.")]
        [StringLength(100, MinimumLength = 5, ErrorMessage = "Password should be at least 5 symbols and less then 100 symbols length.")]
        public string PasswordHash { get; set; }

        [Required(ErrorMessage = "Email required.")]
        [StringLength(50, MinimumLength = 1, ErrorMessage = "Email should be less then 50 symbols length")]
        [RegularExpression(@"^[a-zA-Z]\w*@[a-zA-Z]*\.[a-zA-Z]{2,4}$", ErrorMessage = "Enter valid Email.")]
        public string Email { get; set; }

        public virtual Player Player { get; set; }
    }
}
