//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyGame.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Player
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Name required.")]
        [StringLength(50, MinimumLength = 1, ErrorMessage = "Name should be less then 50 symbols length.")]
        [RegularExpression("^[a-zA-Z]*$", ErrorMessage = "Name should consist of letters only.")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Surname required.")]
        [StringLength(50, MinimumLength = 1, ErrorMessage = "Surname should less then 50 symbols length.")]
        [RegularExpression("^[a-zA-Z]*$", ErrorMessage = "Surname should consist of letters only.")]
        public string Surname { get; set; }

        public virtual Login Login { get; set; }
    }
}
